/* // 布局风格【响应式布局】
export const ADMIN_LAYOUT_STYLE = "ADMIN_LAYOUT_STYLE";
// 固定布局【顶部导航、标签导航、面包屑导航、尾部导航、侧边菜单栏】
export const ADMIN_FIX_LAYOUT = "ADMIN_FIX_LAYOUT";
// 展示布局【顶部导航、标签导航、面包屑导航、尾部导航、侧边栏、侧边栏Logo】
export const ADMIN_SHOW_LAYOUT = "ADMIN_SHOW_LAYOUT";
// 全屏
export const FULL_SCREEN = "FULL_SCREEN";

export const ADMIN_COLLAPSED_LAYOUT = "ADMIN_COLLAPSED_LAYOUT"; */

export const OAUTH2_MUTATION_TYPE = {
  NAMESPACE: "oauth2/",
  SET_GITHUB: "SET_GITHUB",
  SET_WECHAT: "SET_WECHAT",
  SET_QQ: "SET_QQ"
};

export const ADMIN_MUTATION_TYPE = {
  NAMESPACE: "admin/",
  SHOW_DRAWER: "SHOW_DRAWER",
  LOADING: "LOADING",
  SET_LAYOUT_SETTING: "SET_LAYOUT_SETTING",
  SET_THEME_SETTING: "SET_THEME_SETTING",
  SET_IS_MOBILE: "SET_IS_MOBILE"
};

export const IDENTITY_MUTATION_TYPE = {
  NAMESPACE: "identity/",
  SET_IDENTITY: "SET_IDENTITY",
  SET_ROLES: "SET_ROLES",
  SET_PERMISSIONS: "SET_PERMISSIONS",
  SET_TOKEN: "SET_TOKEN",
  SET_OAUTH2: "SET_OAUTH2",
  SET_OAUTH2_THIRDPARTY: "SET_OAUTH2_THIRDPARTY",
  // GET_IDENTITY: "GET_IDENTITY",
  // GET_ROLES: "GET_ROLES",
  // GET_PERMISSIONS: "GET_PERMISSIONS",
  BIND_MAIL: "BIND_MAIL",
  BIND_MOBILE: "BIND_MOBILE",
  UPLOAD_AVATAR: "UPLOAD_AVATAR",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT"
};

export const PVTNOTE_MUTATION_TYPE = {
  NAMESPACE: "pvtnote/",
  SET_NOTE_GROUPS: "SET_NOTE_GROUPS"
};

export const WEBSOCKET_MUTATION_TYPE = {
  name: "websocket",
  NAMESPACE: "websocket/",
  SET_STOMPCLIENT: "SET_STOMPCLIENT",
  GET_STOMPCLIENT: "GET_STOMPCLIENT",
  GET_SUBSCRIBE: "GET_SUBSCRIBE",
  DELETE_SUBSCRIBE: "DELETE_SUBSCRIBE",
  SET_SUBSCRIBE: "SET_SUBSCRIBE"
};
